// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buzkoptlhfmfuaipqfmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1emtvcHRsaGZtZnVhaXBxZm1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NzQyNDEsImV4cCI6MjA1MjA1MDI0MX0.QKXeauuqg_2j4Plug23vETD5KEAKUansFZSwaSu_QX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);